POST http://localhost:3001/api/links
Content-Type: application/json

{
  "platform": {
    "value": "twitter",
    "label": "Twitter",
    "icon": "twitterIcon"
  },
   "link": "https://twitter.com/example"
}
