### Get Authenticated User
GET http://localhost:3001/api/auth/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTczOTc5NDYwMiwiZXhwIjoxNzM5Nzk4MjAyfQ.MRrw2VD1a94XeIckWeECOjr3E9JnTx-ZqW-lu9Pwrw8